Pretty printer
serokell/cardano-sl pull request #1
Opened 2018-03-25 21:40 UTC by Dolgakov

Implement: 
- pprExpr (with and without indentation)
- pprLit

Refactor:
- Change ExprGroup type to AtLeastTwo a a [a]

2018-03-25 23:09 UTC, int-index requested changes

2018-03-25 23:09 UTC, int-index commented on auxx/src/Lang/Syntax.hs
> +fromList_ :: [a] -> AtLeastTwo a
I don't like this function, we don't need it.

2018-03-25 23:09 UTC, int-index commented on auxx/src/Lang/Interpreter.hs
> +evalExprGroup altExprs = case (Lang.toList_ altExprs) of
Instead of calling `toList_` and then doing an unsafe pattern match, just don't call it and do a safe pattern match.

2018-03-25 23:09 UTC, int-index commented on auxx/src/Printer.hs
> +    ppList []     = error "bug: use only with AtLeastTwo"
If a function can't deal with an empty list, its input type should be `NonEmpty`.

2018-03-26 17:20 UTC, dniku requested changes
Please have a look at my PR into your branch [here](https://github.com/serokell/cardano-sl/pull/2). I fixed some style issues there. In particular:

* Please don't leave commented-out code.
* Use a prettifier.
* Don't write super long lines.
* Use consistent style (@int-index suggested the name `ppr*` instead of `pp*`; you have `pprExprNoIdent` and `ppProcCall`, for example).
* Review your changes before creating a PR via the Github UI.

_Wink-wink_ merging my PR into your branch will make it easier to review the logic in your PR ;)

2018-03-26 20:05 UTC, merged